# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [11]:
print(np.__version__)
print(np.show_config())

1.15.0rc2
lapack_mkl_info:
    libraries = ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_rt']
    include_dirs = ['C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2018/windows/mkl/include']
    library_dirs = ['C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2018/windows/mkl/lib/intel64_win']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_rt']
    include_dirs = ['C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2018/windows/mkl/include']
    library_dirs = ['C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2018/windows/mkl/lib/intel64_win']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_rt']
    include_dirs = ['C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2018/windows/mkl/include']
    library_dirs = ['C:/Program Files (x86)/IntelSWT

In [13]:
A = np.zeros(shape=(10,))
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [26]:
print(np.size(A))
print(A.nbytes)
print(A.itemsize)
print(A.dtype)
# itemsize
# itemsize(A)
# print(np.itemsize(A))

10
80
8
float64


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [30]:
np.info('array')

     *** Found in numpy ***
array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.  This argument can only be used to 'upcast' the array.  For
    downcasting, use the .astype(t) method.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array wil

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [34]:
B = np.zeros(shape=(10,))
B[4] = 1.0
print(B)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [39]:
C = np.arange(10,49,1)
print(C)
print(C.itemsize)
print(C.size)
np.info('arange')

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
4
39
     *** Found in numpy ***
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use ``linspace`` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating 

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [47]:
D = np.random.randn(10,2,3)
print(D)
E = D[::-2]
print(E)

[[[ 1.24545939  1.24736595 -0.75737952]
  [ 3.2908534   0.27382649 -0.65054965]]

 [[-0.43155741  0.56908913 -0.78043488]
  [-0.84781545  2.15448046  0.23819801]]

 [[ 1.29511492  1.90166683 -0.45179711]
  [-0.14317947 -0.99881942 -0.57876741]]

 [[-2.68215848  1.13342289 -0.01780418]
  [-0.0275603   0.79979279  1.1901257 ]]

 [[ 0.69326124 -1.02739384 -0.33138523]
  [ 0.57527366  0.66535176  1.0932121 ]]

 [[-3.03257101  0.06110976  0.72016178]
  [-0.63731597  0.05045094  0.0737084 ]]

 [[-0.59658371  0.06345038  1.13013119]
  [ 0.57263605  0.61811782 -1.10153237]]

 [[-0.62423993  0.41504267  2.05188959]
  [ 1.7957694   1.13579747  1.13645006]]

 [[-0.46701734 -0.95838727 -0.79776352]
  [ 0.11810018  1.13887866 -1.75132361]]

 [[ 1.19611054 -1.6209479   0.26388584]
  [ 0.02612844 -0.48545635  0.37281679]]]
[[[ 1.19611054 -1.6209479   0.26388584]
  [ 0.02612844 -0.48545635  0.37281679]]

 [[-0.62423993  0.41504267  2.05188959]
  [ 1.7957694   1.13579747  1.13645006]]

 [[-3.03257101  

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [50]:
F =np.arange(9.)
print(F)
G = F.reshape(3,3)
print(G)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [71]:
H = np.array([1,2,0,0,4,0,9,8,0,0,0,12])
# H = [1,2,0,0,4,0]
H = H.reshape(3,2,2)
print(H)
idx = np.nonzero(H)
HH = H[idx]
print(idx)
idxx = np.transpose(np.nonzero(H))
print(idxx)
print(H[idxx])
np.info('nonzero')

[[[ 1  2]
  [ 0  0]]

 [[ 4  0]
  [ 9  8]]

 [[ 0  0]
  [ 0 12]]]
(array([0, 0, 1, 1, 1, 2], dtype=int64), array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 0, 0, 1, 1], dtype=int64))
[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]
 [2 1 1]]
[[[[ 1  2]
   [ 0  0]]

  [[ 1  2]
   [ 0  0]]

  [[ 1  2]
   [ 0  0]]]


 [[[ 1  2]
   [ 0  0]]

  [[ 1  2]
   [ 0  0]]

  [[ 4  0]
   [ 9  8]]]


 [[[ 4  0]
   [ 9  8]]

  [[ 1  2]
   [ 0  0]]

  [[ 1  2]
   [ 0  0]]]


 [[[ 4  0]
   [ 9  8]]

  [[ 4  0]
   [ 9  8]]

  [[ 1  2]
   [ 0  0]]]


 [[[ 4  0]
   [ 9  8]]

  [[ 4  0]
   [ 9  8]]

  [[ 4  0]
   [ 9  8]]]


 [[[ 0  0]
   [ 0 12]]

  [[ 4  0]
   [ 9  8]]

  [[ 4  0]
   [ 9  8]]]]
     *** Found in numpy ***
 nonzero(a)

Return the indices of the elements that are non-zero.

Returns a tuple of arrays, one for each dimension of `a`,
containing the indices of the non-zero elements in that
dimension. The values in `a` are always tested and returned in
row-major, C-style order. The correspondin

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [72]:
J = np.eye(3,3)
print(J)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [78]:
# np.info('random')
J = np.random.random((3,3,3))
print(J)

[[[0.49666929 0.68671708 0.69922436]
  [0.29019553 0.7036906  0.19758205]
  [0.01057367 0.00304161 0.52459939]]

 [[0.18368503 0.96770791 0.39925511]
  [0.84453732 0.49015331 0.93618945]
  [0.83870149 0.01767041 0.83089887]]

 [[0.52937852 0.67076162 0.10120104]
  [0.35766572 0.2460791  0.27552611]
  [0.96465268 0.35500735 0.69522513]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [82]:
J = np.random.random((10,10))
min_J = np.min(J)
max_J = np.max(J)
print(J)
print(min_J)
print(max_J)
np.info('min')

[[0.12945044 0.38309604 0.52590873 0.97434897 0.12085074 0.30757591
  0.71378504 0.98290917 0.67278073 0.85362462]
 [0.2126014  0.47458205 0.14256943 0.73767886 0.16631911 0.55762416
  0.06733596 0.02462009 0.08547867 0.35828646]
 [0.29550151 0.13426711 0.2802087  0.44056127 0.82469093 0.32108569
  0.23304864 0.11178497 0.14251611 0.4647894 ]
 [0.76516236 0.41199795 0.83922707 0.92921947 0.02795881 0.20180034
  0.30736941 0.64493794 0.36514502 0.35472333]
 [0.44279506 0.78652542 0.15300285 0.77651999 0.9237936  0.22090346
  0.611434   0.23148919 0.55133653 0.85622714]
 [0.9600085  0.03948223 0.29389975 0.21400058 0.57631164 0.18420015
  0.13382193 0.83161316 0.05031244 0.00393913]
 [0.56781082 0.59090442 0.05149334 0.95695901 0.53493206 0.65546794
  0.87634932 0.00347526 0.64362626 0.52218516]
 [0.45528106 0.21613896 0.06525017 0.15501816 0.81749324 0.15398276
  0.9695504  0.26512072 0.74150354 0.17111454]
 [0.86831676 0.39344648 0.10757879 0.48690593 0.85209637 0.07875173
  0.52405916

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [2]:
import  numpy as np
A = np.random.random(30)
print(A)
print(np.mean(A))

[0.78856313 0.71135176 0.45994173 0.65073661 0.97368083 0.83499845
 0.2045889  0.69704546 0.65621602 0.56412159 0.86617115 0.10424023
 0.42674869 0.62495071 0.03540168 0.27693673 0.1085654  0.35237917
 0.14720857 0.86219931 0.97534184 0.61072669 0.61595796 0.52774585
 0.6493766  0.81309016 0.51136545 0.02940042 0.43755658 0.68159692]
0.5399401516707386


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [6]:
B = np.ones(shape=(4,6))
print(B)
B[1:-1,1:-1] = 0.0
print(B)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [15]:
C = np.random.randn(6,9)
print(C)
np.pad(C,((2,1),(1,2)),'constant',constant_values=((1.1,1.2),(2.1,2.2)))
# np.info('pad')

[[-8.44736455e-01  6.52049928e-01  6.97200368e-02 -5.26824419e-01
  -9.87445475e-01 -1.21263424e-01  3.24266632e-01 -4.76850004e-01
  -1.09310392e+00]
 [-7.96851699e-01 -1.65527150e-03  1.02044699e+00  6.57822044e-01
  -7.57080811e-01 -1.52959651e+00  1.07066117e+00 -4.54050604e-01
  -4.85568668e-01]
 [-4.79119568e-01  9.67572391e-01  1.16395135e+00  1.11132842e+00
  -1.46242959e+00 -4.46011192e-01 -6.63439842e-01  4.99625186e-01
   6.14527890e-02]
 [ 9.57715345e-01  1.31344627e+00  5.28927774e-01 -8.20106506e-01
  -4.53593631e-01 -5.19433325e-01  1.32270617e+00 -9.31873294e-01
  -6.75228320e-01]
 [ 2.80011790e+00 -5.12439923e-01 -3.22269008e-01  1.15849881e+00
   9.43318791e-01  6.08811265e-01  7.16652693e-01  8.83770551e-01
   7.66948116e-01]
 [ 1.00426919e-02 -9.38103919e-01 -4.60784106e-01  4.17921959e-01
  -2.57028592e-01 -1.09884327e+00 -4.81597597e-01  5.87451316e-01
  -1.69866777e+00]]


array([[ 2.10000000e+00,  1.10000000e+00,  1.10000000e+00,
         1.10000000e+00,  1.10000000e+00,  1.10000000e+00,
         1.10000000e+00,  1.10000000e+00,  1.10000000e+00,
         1.10000000e+00,  2.20000000e+00,  2.20000000e+00],
       [ 2.10000000e+00,  1.10000000e+00,  1.10000000e+00,
         1.10000000e+00,  1.10000000e+00,  1.10000000e+00,
         1.10000000e+00,  1.10000000e+00,  1.10000000e+00,
         1.10000000e+00,  2.20000000e+00,  2.20000000e+00],
       [ 2.10000000e+00, -8.44736455e-01,  6.52049928e-01,
         6.97200368e-02, -5.26824419e-01, -9.87445475e-01,
        -1.21263424e-01,  3.24266632e-01, -4.76850004e-01,
        -1.09310392e+00,  2.20000000e+00,  2.20000000e+00],
       [ 2.10000000e+00, -7.96851699e-01, -1.65527150e-03,
         1.02044699e+00,  6.57822044e-01, -7.57080811e-01,
        -1.52959651e+00,  1.07066117e+00, -4.54050604e-01,
        -4.85568668e-01,  2.20000000e+00,  2.20000000e+00],
       [ 2.10000000e+00, -4.79119568e-01,  9.6757239

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [32]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(3 * 0.1)
print(3*0.1)

nan
False
False
nan
True
0.30000000000000004
0.30000000000000004


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [33]:
A = np.diag([1,2,3,4])
print(A)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [81]:
A = np.zeros(shape=(8,8))
A[::2,::2] = 1.0 
A[::-2,::-2] = 1.0 
# A[:,::2] = 1 - A[:,::2]
# A = A.T
# A[::2] = 1.0
# A = A.T
# # print(A[::-2])
# A[::-2] = 1 - A[::-2]
# A.T[::2] = 1.0
print(A)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [51]:
A = np.random.rand(6,7,8)
print(A[0,0,0])
print(A[1,0,0])
print(A[2,0,0])
# np.info('unravel_index')
print(A[np.unravel_index((0,56,112),A.shape)])

0.43923143133501674
0.004061556154298929
0.630155625294341
[0.43923143 0.00406156 0.63015563]


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [7]:
import numpy as np
A  = np.array([[0.,1.],[1.,0.]])
print(A)
B = np.tile(A,(4,4))
print(B)
# np.info('tile')

[[0. 1.]
 [1. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - mean) / std)

In [11]:
A = np.random.random((5,5))
B = A - np.mean(A) / np.std(A)
print(B)
np.info('std')

[[-1.13092038 -1.31558785 -0.9821183  -1.05298076 -0.45169737]
 [-0.48760238 -0.81164902 -0.4993193  -1.35097227 -0.62352352]
 [-0.5247452  -0.50214602 -1.37862178 -1.1174702  -1.32479893]
 [-0.98330347 -0.59533771 -1.42177895 -1.2203672  -0.49702155]
 [-1.07666387 -0.8581876  -1.31843127 -1.38171681 -0.69360052]]
     *** Found in numpy ***
 std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)

Compute the standard deviation along the specified axis.

Returns the standard deviation, a measure of the spread of a distribution,
of the array elements. The standard deviation is computed for the
flattened array by default, otherwise over the specified axis.

Parameters
----------
a : array_like
    Calculate the standard deviation of these values.
axis : None or int or tuple of ints, optional
    Axis or axes along which the standard deviation is computed. The
    default is to compute the standard deviation of the flattened array.

    .. versionadded:: 1.7.0

    If this i

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [21]:
mytype = np.dtype([('r',np.ubyte),('g',np.ubyte),('b',np.ubyte),('a',np.ubyte)])
print(mytype)
colrtArray = np.array([[(3,4,5,155),(3,4,5,155)],[(3,4,5,155),(3,4,5,155)]],dtype=mytype)
print(colrtArray)
print(colrtArray.shape)
# np.info('dtype')

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
[[(3, 4, 5, 155) (3, 4, 5, 155)]
 [(3, 4, 5, 155) (3, 4, 5, 155)]]
(2, 2)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [38]:
A = np.random.randn(5,3)
print('A:',A)
B = np.random.randn(3,2)
print('B:',B)
C = np.matrix(A) *  np.matrix(B)
print('C:',C)
D = np.dot(A,B)
D = A.dot(B)
print('D:',D)
E = np.matmul(A,B)
print('E:',E)

#####
A = np.random.randn(4,3,3)
B = np.random.randn(4,3,3)
F = np.dot(A,B)
print('F:',F)
print(A[1,2,1]* B[1,2,1],)
print(F[1,2,1],)
np.info('dot')

A: [[-0.20475981 -0.18909519 -3.03174268]
 [ 1.88776469  0.41961265 -0.82379059]
 [-0.08603374 -1.59703415 -0.08071019]
 [ 1.45996096 -0.22274211  1.79277023]
 [ 0.2682207   0.77368019  0.6003705 ]]
B: [[ 0.9060565   0.94594924]
 [ 0.91797042 -0.84251643]
 [-0.0021255   0.20469629]]
C: [[-0.35266376 -0.65496306]
 [ 2.09736445  1.26357215]
 [-1.54380999  1.24762288]
 [ 1.11452592  1.93568627]
 [ 0.95196254 -0.27522149]]
D: [[-0.35266376 -0.65496306]
 [ 2.09736445  1.26357215]
 [-1.54380999  1.24762288]
 [ 1.11452592  1.93568627]
 [ 0.95196254 -0.27522149]]
E: [[-0.35266376 -0.65496306]
 [ 2.09736445  1.26357215]
 [-1.54380999  1.24762288]
 [ 1.11452592  1.93568627]
 [ 0.95196254 -0.27522149]]
F: [[[[-4.05307236e-01  3.94825264e-01  2.30083327e-01]
   [-1.59095937e+00  1.25961583e-01  2.45697604e-01]
   [ 1.22704240e+00 -7.42435318e-01 -1.31850164e+00]
   [ 7.86656389e-01  2.35107035e-01  8.32062026e-01]]

  [[ 1.52765656e+00  9.26918809e-01 -1.65473139e+00]
   [-2.39570003e+00 -1.241594

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray | np.unique)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)